=== politecnicoProyect2022/XML_Ejercicio2/exercise2.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="pedidos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pedido" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="numeroSerie" type="xs:integer"/>
                            <xs:element name="cantidad" type="xs:integer"/>
                            <xs:element name="peso" type="xs:integer" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== politecnicoProyect2022/XML_Ejercicio2/exercise2.xml
<?xml version="1.0" encoding="UTF-8"?>
<pedidos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="exercise2.xsd">
<!--DOCTYPE pedidos SYSTEM "exercise2.dtd">

<pedidos-->
    <pedido>
        <numeroSerie>455646</numeroSerie>
        <cantidad>56</cantidad>
        <peso>23</peso>
    </pedido>
    <pedido>
        <numeroSerie>34756</numeroSerie>
        <cantidad>24</cantidad>
    </pedido>
</pedidos>
